#!/usr/bin/env python3
"""
Turn one job of the event splitter (jobN.json) into the CWL inputs file of
cwl/stepchain_6steps.cwl (one StepParams record per step).

Request-level values (release, arch, PSet, output module, memory) come from
request.json and the PSets directory; job-level values (events, lumi, run,
threads) are read back from the precomputed tweaks in jobN.json. The
fileNames / fileName tweaks are dropped: in CWL they are derived from how the
steps are wired (see cwl/tools/pset_tweak.cwl).

Usage:
  make_job_inputs.py --request request.json --job job38.json --psets PSets/ \
      --output job38.yml [--max-events 10]

Standard library only.
"""
import argparse
import json
import os
import re
import sys

# Tweak key -> StepParams field, for the values that are integers in the tweak string.
TWEAK_FIELDS = {
    "process.options.numberOfThreads": "number_of_threads",
    "process.options.numberOfStreams": "number_of_streams",
    "process.maxEvents": "max_events",
    "process.source.firstEvent": "first_event",
    "process.source.firstLuminosityBlock": "first_lumi",
    "process.source.firstRun": "first_run",
}
INT_IN_TWEAK = re.compile(r"int32\((-?\d+)\)\)*$")
OUTPUT_MODULE_DEF = re.compile(r"^process\.(\w+)\s*=\s*cms\.OutputModule\(", re.M)
OUTPUT_FILENAME_TWEAK = re.compile(r"^process\.(\w+)\.fileName$")


def tweak_int(key, value):
    """customTypeCms.untracked.uint32(38) -> 38; ...PSet(input=cms.untracked.int32(830)) -> 830."""
    match = INT_IN_TWEAK.search(value)
    if not match:
        raise ValueError("Cannot read an integer from tweak %s = %s" % (key, value))
    return int(match.group(1))


def find_pset(psets_dir, step_num, step_name):
    path = os.path.join(psets_dir, "PSet_cmsRun%d_%s.py" % (step_num, step_name))
    if not os.path.isfile(path):
        raise FileNotFoundError("Base PSet not found: %s" % path)
    return path


def output_module_for_step(step_tweak, pset_path):
    """Module whose file goes to the next step: the one the splitter renamed, else the PSet's only one."""
    for key in step_tweak:
        match = OUTPUT_FILENAME_TWEAK.match(key)
        if match:
            return match.group(1)
    with open(pset_path) as f:
        modules = OUTPUT_MODULE_DEF.findall(f.read())
    if len(modules) != 1:
        raise ValueError("Cannot pick the output module of %s among %s" % (pset_path, modules))
    return modules[0]


def build_step_params(req, job, psets_dir, max_events=None):
    """Return {"step1": {...}, ..., "stepN": {...}} for the CWL inputs file."""
    num_steps = int(req["StepChain"])
    steps = {}
    for step_num in range(1, num_steps + 1):
        step = req["Step%d" % step_num]
        step_tweak = job["tweaks"][str(step_num)]
        if isinstance(step_tweak, list):
            raise NotImplementedError("NumCopies > 1 is not supported by the CWL workflow yet")
        arch = step.get("ScramArch") or req["ScramArch"]
        pset = find_pset(psets_dir, step_num, step["StepName"])
        params = {
            "cmssw_version": step.get("CMSSWVersion") or req["CMSSWVersion"],
            "scram_arch": arch[0] if isinstance(arch, list) else arch,
            "pset": pset,
            "output_module": output_module_for_step(step_tweak, pset),
            "memory_mb": int(step.get("Memory") or req["Memory"]),
        }
        for key, field in TWEAK_FIELDS.items():
            if key in step_tweak:
                params[field] = tweak_int(key, step_tweak[key])
        if step_num == 1 and max_events is not None:
            params["max_events"] = max_events
        steps["step%d" % step_num] = params
    return steps


def to_yaml(job_index, request_name, steps, output_dir):
    """Small fixed-shape YAML writer (keeps this script dependency free)."""
    lines = [
        "# CWL inputs for job %d of %s" % (job_index, request_name),
        "# Generated by cwl/scripts/make_job_inputs.py; run with:",
        "#   cwltool cwl/stepchain_6steps.cwl <this file>",
    ]
    for step_key, params in steps.items():
        lines.append("%s:" % step_key)
        for field, value in params.items():
            if field == "pset":
                rel = os.path.relpath(value, output_dir)
                lines.append("  pset: {class: File, location: %s}" % rel)
            else:
                lines.append("  %s: %s" % (field, value))
    return "\n".join(lines) + "\n"


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--request", required=True, help="ReqMgr request JSON")
    parser.add_argument("--job", required=True, help="jobN.json from event_splitter")
    parser.add_argument("--psets", required=True, help="Directory with PSet_cmsRunN_<StepName>.py files")
    parser.add_argument("--output", required=True, help="CWL inputs file to write (YAML)")
    parser.add_argument("--max-events", type=int,
                        help="Override step 1 maxEvents, for quick tests (the real job uses the splitter's value)")
    return parser.parse_args()


def main():
    args = parse_args()
    with open(args.request) as f:
        req = json.load(f)
    with open(args.job) as f:
        job = json.load(f)
    steps = build_step_params(req, job, args.psets, max_events=args.max_events)
    output_dir = os.path.dirname(os.path.abspath(args.output))
    request_name = req.get("RequestName") or req.get("_id", "unknown request")
    with open(args.output, "w") as f:
        f.write(to_yaml(job["job_index"], request_name, steps, output_dir))
    print("Wrote %s (%d steps)" % (args.output, len(steps)), file=sys.stderr)


if __name__ == "__main__":
    main()
