sandbox: {class: File, path: "/afs/cern.ch/user/v/vchakrav/reqmgr2cwl/artifacts/cmsunified_task_TOP-RunIII2024Summer24GS-00003__v1_T_250915_213421_7140-Sandbox.tar.bz2"}
job_package: {class: File, path: "/afs/cern.ch/user/v/vchakrav/reqmgr2cwl/artifacts/JobPackage.pkl"}
unpacker_script: {class: File, path: "/afs/cern.ch/user/v/vchakrav/reqmgr2cwl/artifacts/.generated/Unpacker.py"}
run_script: {class: File, path: "/afs/cern.ch/user/v/vchakrav/reqmgr2cwl/tools/scripts/run_wmcore_job.sh"}
reqmgr2_json: {class: File, path: "/afs/cern.ch/user/v/vchakrav/reqmgr2cwl/artifacts/cmsunified_task_TOP-RunIII2024Summer24GS-00003__v1_T_250915_213421_7140.json"}
job_index: 1459333
num_cores: 1
memory_mb: 16000
cmssw_container: "cmssw-el8"
step_name: "TOP-RunIII2024Summer24DRPremix-00020_1MergeAODSIMoutput"
request_name: "cmsunified_task_TOP-RunIII2024Summer24GS-00003__v1_T_250915_213421_7140"
request_type: "StepChain"
request_status: "running-open"
requestor: "cmsunified"
prep_id: "task_TOP-RunIII2024Summer24GS-00003"
dbs_url: "https://cmsweb-prod.cern.ch/dbs/prod/global/DBSReader"
config_cache_url: "https://cmsweb.cern.ch/couchdb"
campaign: "RunIII2024Summer24GS"
splitting_algo: "unknown"
events_per_job: ""
primary_dataset: ""
input_dataset: ""
config_cache_id: ""
cmssw_version: "CMSSW_15_0_13_patch2"
scram_arch: "el8_amd64_gcc12"
global_tag: "150X_mcRun3_2024_realistic_v2"
acquisition_era: ""
processing_string: ""
site_whitelist: ["T1_DE_KIT", "T1_ES_PIC", "T1_FR_CCIN2P3", "T1_IT_CNAF", "T1_PL_NCBJ", "T1_UK_RAL", "T1_US_FNAL", "T2_AT_Vienna", "T2_BE_IIHE", "T2_BE_UCL", "T2_BR_SPRACE", "T2_CH_CERN", "T2_CH_CERN_HLT", "T2_CH_CERN_P5", "T2_CH_CSCS", "T2_DE_DESY", "T2_DE_RWTH", "T2_EE_Estonia", "T2_ES_CIEMAT", "T2_ES_IFCA", "T2_FI_HIP", "T2_FR_GRIF", "T2_IT_Bari", "T2_IT_Legnaro", "T2_IT_Pisa", "T2_KR_KISTI", "T2_PL_Cyfronet", "T2_PT_NCG_Lisbon", "T2_UA_KIPT", "T2_UK_London_Brunel", "T2_UK_London_IC", "T2_UK_SGrid_RALPP", "T2_US_Caltech", "T2_US_Florida", "T2_US_MIT", "T2_US_Nebraska", "T2_US_Purdue", "T2_US_UCSD", "T2_US_Vanderbilt", "T2_US_Wisconsin", "T3_UK_London_RHUL", "T3_UK_SGrid_Oxford", "T3_US_Anvil", "T3_US_Baylor", "T3_US_Colorado", "T3_US_Lancium", "T3_US_NERSC", "T3_US_OSG", "T3_US_PSC", "T3_US_SDSC", "T3_US_TACC"]
output_datasets: ["/TTto4Q-4Jets-1NLO3LO_TuneSherpaDef_13p6TeV_sherpaMEPS/RunIII2024Summer24DRPremix-140X_mcRun3_2024_realistic_v26-v2/AODSIM", "/TTto4Q-4Jets-1NLO3LO_TuneSherpaDef_13p6TeV_sherpaMEPS/RunIII2024Summer24MiniAODv6-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM", "/TTto4Q-4Jets-1NLO3LO_TuneSherpaDef_13p6TeV_sherpaMEPS/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM"]
